// Scenario definitions for aim trainer
import { Scenario } from './types';

export const scenarios: Scenario[] = [
  {
    id: 'static-grid',
    name: 'Static Grid',
    description: 'Click static targets as fast as possible. Targets respawn on hit.',
    duration: 30,
    targetCount: 6,
    targetSize: 25,
    movement: 'static',
    scoring: 'tps',
    category: 'precision',
  },
  {
    id: 'tiny-15s',
    name: 'Tiny 15s',
    description: '15 seconds. Tiny targets. Mimics mouseaccuracy.com tiny mode.',
    duration: 15,
    targetCount: 10,
    targetSize: 12,
    movement: 'static',
    scoring: 'tps',
    category: 'precision',
  },
  {
    id: 'strafing-click',
    name: 'Strafing Click',
    description: 'Hit targets that move left and right. Tests prediction and timing.',
    duration: 30,
    targetCount: 6,
    targetSize: 30,
    movement: 'strafe',
    scoring: 'accuracy',
    speed: 5,
    category: 'precision',
  },
  {
    id: 'smooth-track',
    name: 'Smooth Track',
    description: 'Keep your cursor on the target. No clicking required.',
    duration: 30,
    targetCount: 1,
    targetSize: 40,
    movement: 'smooth',
    scoring: 'tracking',
    speed: 2,
    category: 'tracking',
  },
  {
    id: 'adaptive-track',
    name: 'Adaptive Track',
    description: 'Speed increases with accuracy! Higher speed = more points. Can you keep up?',
    duration: 30,
    targetCount: 1,
    targetSize: 45,
    movement: 'smooth',
    scoring: 'adaptive',
    speed: 1.5,
    category: 'tracking',
  },
  {
    id: 'benchmark',
    name: 'Benchmark',
    description: 'Auto-plays to test performance. Logs FPS, frame times, and render stats.',
    duration: 10,
    targetCount: 6,
    targetSize: 25,
    movement: 'static',
    scoring: 'benchmark',
    autoPlay: true,
    category: 'calibration',
  },
  {
    id: 'reaction',
    name: 'Reaction Test',
    description: 'Best of 5. Target appears, click anywhere to react. Random delays.',
    duration: 60,
    targetCount: 1,
    targetSize: 40,
    movement: 'static',
    scoring: 'reaction',
    clickLimit: 5,
    category: 'speed',
  },
  {
    id: 'visual-reaction',
    name: 'Visual Reaction',
    description: 'Best of 5. Wait for the screen to turn RED, then click!',
    duration: 60,
    targetCount: 0,
    targetSize: 0,
    movement: 'static',
    scoring: 'reaction',
    clickLimit: 5,
    category: 'speed',
  },
  {
    id: 'target-frenzy-100',
    name: 'Target Frenzy 100',
    description: '100 static targets spawned at once. Clear them all as fast as possible.',
    duration: 999,
    targetCount: 100,
    targetSize: 20,
    movement: 'static',
    scoring: 'tps',
    clickLimit: 100,
    noRespawn: true,
    category: 'challenge',
  },
  {
    id: 'strafing-frenzy-100',
    name: 'Strafing Frenzy 100',
    description: '100 moving targets! They strafe left and right. Clear them all.',
    duration: 999,
    targetCount: 100,
    targetSize: 22,
    movement: 'strafe',
    scoring: 'tps',
    speed: 4,
    clickLimit: 100,
    noRespawn: true,
    category: 'challenge',
  },
  {
    id: 'compass-rose',
    name: 'Compass Rose',
    description: 'Hit all 8 directions from center. Tests your mousepad coverage and edge-to-edge precision.',
    duration: 60,
    targetCount: 9,
    targetSize: 30,
    movement: 'static',
    scoring: 'accuracy',
    pattern: 'compass',
    category: 'calibration',
  },
  {
    id: 'linear-calibration',
    name: 'Sensitivity Calibration',
    description: 'Measure your effective DPI (eDPI) by moving your mouse exactly 10cm horizontally.',
    duration: -1,
    targetCount: 0,
    targetSize: 0,
    movement: 'static',
    scoring: 'accuracy', // Not used, special logic
    category: 'calibration',
  },
];

export function getScenario(id: string): Scenario | undefined {
  return scenarios.find(s => s.id === id);
}
